package org.nohi.mybatis.entity;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.Proxy;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by NOHI MyBatis Generator.
 * This class corresponds to the database table TMybatisEntity
 */
@Setter
@Getter
@Entity
@Table(name = "T_MYBATIS")
@Proxy(lazy = false)
public class TMybatisEntity implements Serializable {
    /**
     *   主键
     *   T_MYBATIS.t_id
     */
    @Id
    @GeneratedValue
    private Integer tId;

    /**
     *   姓名
     *   T_MYBATIS.t_name
     */
    private String tName;

    /**
     *   生日
     *   T_MYBATIS.t_birthday
     */
    private Date tBirthday;

    /**
     *   你猜
     *   T_MYBATIS.t_salay
     */
    private BigDecimal tSalay;
}
