package org.nohi.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by NOHI MyBatis Generator.
 * This class corresponds to the database table OcrmFCiRecordCheckDataEntity
 */
@Entity
@Table(name = "JPA_TEST")
public class JpaTestEntity {
    /**
     *   无业务含义主键
     *   OCRM_F_CI_RECORD_CHECK_DATA.PROW_ID
     */
    @Id
    @Column(name="PROW_ID")
    private String prowId;

    /**
     *   保险公司代码
     *   OCRM_F_CI_RECORD_CHECK_DATA.INSURACE_CODE
     */
    @Column(name="INSURACE_CODE")
    private String insuraceCode;

    /**
     *   ETL日期
     *   OCRM_F_CI_RECORD_CHECK_DATA.ETL_DATE
     */
    @Column(name="ETL_DATE")
    private Date etlDate;

    /**
     *   入库次数
     *   OCRM_F_CI_RECORD_CHECK_DATA.TIMES
     */
    @Column(name="TIMES")
    private Integer times;

    /**
     *   LAST_UPDATE_TS
     *   OCRM_F_CI_RECORD_CHECK_DATA.LAST_UPDATE_TS
     */
    @Column(name="LAST_UPDATE_TS")
    private Date lastUpdateTs;

    @Column(name="CREATE_USER")
    private String createUser;

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * getter 无业务含义主键
     * @return the value of OCRM_F_CI_RECORD_CHECK_DATA.PROW_ID
     */
    public String getProwId() {
        return prowId;
    }

    /**
     * setter 无业务含义主键
     * @param prowId the value for OCRM_F_CI_RECORD_CHECK_DATA.PROW_ID
     */
    public void setProwId(String prowId) {
        this.prowId = prowId == null ? null : prowId.trim();
    }

    /**
     * getter 保险公司代码
     * @return the value of OCRM_F_CI_RECORD_CHECK_DATA.INSURACE_CODE
     */
    public String getInsuraceCode() {
        return insuraceCode;
    }

    /**
     * setter 保险公司代码
     * @param insuraceCode the value for OCRM_F_CI_RECORD_CHECK_DATA.INSURACE_CODE
     */
    public void setInsuraceCode(String insuraceCode) {
        this.insuraceCode = insuraceCode == null ? null : insuraceCode.trim();
    }

    /**
     * getter ETL日期
     * @return the value of OCRM_F_CI_RECORD_CHECK_DATA.ETL_DATE
     */
    public Date getEtlDate() {
        return etlDate;
    }

    /**
     * setter ETL日期
     * @param etlDate the value for OCRM_F_CI_RECORD_CHECK_DATA.ETL_DATE
     */
    public void setEtlDate(Date etlDate) {
        this.etlDate = etlDate;
    }

    /**
     * getter 入库次数
     * @return the value of OCRM_F_CI_RECORD_CHECK_DATA.TIMES
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * setter 入库次数
     * @param times the value for OCRM_F_CI_RECORD_CHECK_DATA.TIMES
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * getter LAST_UPDATE_TS
     * @return the value of OCRM_F_CI_RECORD_CHECK_DATA.LAST_UPDATE_TS
     */
    public Date getLastUpdateTs() {
        return lastUpdateTs;
    }

    /**
     * setter LAST_UPDATE_TS
     * @param lastUpdateTs the value for OCRM_F_CI_RECORD_CHECK_DATA.LAST_UPDATE_TS
     */
    public void setLastUpdateTs(Date lastUpdateTs) {
        this.lastUpdateTs = lastUpdateTs;
    }
}